#!/usr/bin/env python3

"""Measure chunks that exceed the standard four-speaker model capacity."""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path


RECIPE_DIR = Path(__file__).resolve().parent


@dataclass(frozen=True)
class Segment:
    """One speaker activity segment."""

    start: float
    end: float
    speaker: str


@dataclass(frozen=True)
class CapacityReport:
    """Speaker-capacity counts for one dataset split."""

    split: str
    chunks: int
    chunks_over_capacity: int
    maximum_active_speakers: int
    active_speaker_distribution: dict[int, int]


def load_uem(path: Path) -> dict[str, tuple[float, float]]:
    """Load UEM recording bounds."""

    bounds = {}
    for line in path.read_text().splitlines():
        fields = line.split()
        if fields:
            bounds[fields[0]] = (float(fields[-2]), float(fields[-1]))
    return bounds


def load_rttm(path: Path) -> dict[str, list[Segment]]:
    """Load RTTM segments by recording."""

    segments: dict[str, list[Segment]] = defaultdict(list)
    for line in path.read_text().splitlines():
        fields = line.split()
        if not fields:
            continue
        start = float(fields[3])
        speaker = fields[-2] if fields[-2] != "<NA>" else fields[-3]
        segments[fields[1]].append(Segment(start, start + float(fields[4]), speaker))
    return segments


def audit_split(
    name: str,
    directory: Path,
    chunk_shift: int,
    capacity: int,
) -> CapacityReport:
    """Count active speakers in every chunk generated by the training dataset."""

    bounds = load_uem(directory / "all.uem")
    segments = load_rttm(directory / "rttm")
    distribution: Counter[int] = Counter()
    for session_id, (start, end) in bounds.items():
        first = int(start + 1)
        last = int(end - 1)
        chunk_count = int((last - first - 8 + chunk_shift) / chunk_shift)
        for index in range(max(chunk_count, 0)):
            chunk_start = first + index * chunk_shift
            chunk_end = chunk_start + 8
            active = {
                segment.speaker
                for segment in segments[session_id]
                if segment.start < chunk_end and segment.end > chunk_start
            }
            distribution[len(active)] += 1

    chunks = sum(distribution.values())
    return CapacityReport(
        split=name,
        chunks=chunks,
        chunks_over_capacity=sum(count for speaker_count, count in distribution.items() if speaker_count > capacity),
        maximum_active_speakers=max(distribution),
        active_speaker_distribution=dict(sorted(distribution.items())),
    )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-root",
        type=Path,
        default=RECIPE_DIR.parent / "diar_ssl" / "data" / "AMI_AliMeeting_AISHELL4",
    )
    parser.add_argument("--capacity", type=int, default=4)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> None:
    """Audit the standard train and development manifests."""

    args = parse_args()
    root = args.data_root.expanduser().resolve()
    reports = [
        audit_split("train", root / "train", 6, args.capacity),
        audit_split("dev", root / "dev", 8, args.capacity),
    ]
    content = json.dumps([asdict(report) for report in reports], indent=2) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        temporary = args.output.with_suffix(".partial.json")
        temporary.write_text(content)
        temporary.replace(args.output)
    print(content, end="")


if __name__ == "__main__":
    main()
